name: deploy-fly
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'seoworkbench/**'
      - 'Dockerfile.api'
      - 'Dockerfile.worker'
      - 'fly.*.toml'

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy API
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --config fly.api.toml --remote-only

  deploy-worker:
    runs-on: ubuntu-latest
    needs: deploy-api
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Worker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --config fly.worker.toml --remote-only

